// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBPFUJVuKDUiDk5OvWnPSHzJTQbUP1dbg',
    appId: '1:276661864238:web:84629495b922450fd21cbf',
    messagingSenderId: '276661864238',
    projectId: 'fir-authentication-93b7c',
    authDomain: 'fir-authentication-93b7c.firebaseapp.com',
    storageBucket: 'fir-authentication-93b7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTojXlzauabh3RfcGSBcwiikCbOU_4aT8',
    appId: '1:276661864238:android:bb7b0652512a7fc7d21cbf',
    messagingSenderId: '276661864238',
    projectId: 'fir-authentication-93b7c',
    storageBucket: 'fir-authentication-93b7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl9lD5zq9BZL42_j88TwfTn-HBDcpbOIY',
    appId: '1:276661864238:ios:4297d492055ee777d21cbf',
    messagingSenderId: '276661864238',
    projectId: 'fir-authentication-93b7c',
    storageBucket: 'fir-authentication-93b7c.firebasestorage.app',
    androidClientId: '276661864238-c2iaq9i5h013428df7ia6hte6vp6l1qs.apps.googleusercontent.com',
    iosClientId: '276661864238-64nahgmt0vg4bi24nkctg66okqlmik4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.authPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl9lD5zq9BZL42_j88TwfTn-HBDcpbOIY',
    appId: '1:276661864238:ios:4297d492055ee777d21cbf',
    messagingSenderId: '276661864238',
    projectId: 'fir-authentication-93b7c',
    storageBucket: 'fir-authentication-93b7c.firebasestorage.app',
    androidClientId: '276661864238-c2iaq9i5h013428df7ia6hte6vp6l1qs.apps.googleusercontent.com',
    iosClientId: '276661864238-64nahgmt0vg4bi24nkctg66okqlmik4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.authPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBPFUJVuKDUiDk5OvWnPSHzJTQbUP1dbg',
    appId: '1:276661864238:web:80e4d8370328b621d21cbf',
    messagingSenderId: '276661864238',
    projectId: 'fir-authentication-93b7c',
    authDomain: 'fir-authentication-93b7c.firebaseapp.com',
    storageBucket: 'fir-authentication-93b7c.firebasestorage.app',
  );

}